### ISSUE TITLE
[Study] 다이나믹 프로그래밍(0x0A)을 학습하고 문제를 풀이합니다. (@dahae0320)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#10]
## ⌗ Overview
> 다이나믹 프로그래밍(0x0A)을 학습하고 문제를 풀이합니다. (@dahae0320)

다이나믹 프로그래밍 강의를 바탕으로 이론과 문제를 풀이합니다.

## ⚒︎ Task
* [ ] 바킹독 알고리즘 강의의 0x10 챕터 '다이나믹 프로그래밍' 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] Python, Swift에 관련하여 배열 정리
* [ ] 문제집 풀이
