### ISSUE TITLE
[Study] 그리디(0x0B)을 학습하고 문제를 풀이합니다. (@dahae0320)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#11]
## ⌗ Overview
> 그리디(0x0B)을 학습하고 문제를 풀이합니다. (@dahae0320)

바킹독 그리디 강의를 바탕으로 그리디 이론과 문제를 풀이합니다.

## ⚒︎ Task
* [ ] 바킹독 알고리즘 강의의 '그리디' 챕터 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] Python, Swift에 관련하여 배열 정리
* [ ] 문제집 풀이
