### ISSUE TITLE
[Study] 수학(0x0C)을 학습하고 문제를 풀이합니다. (@dadahae)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#13]
## ⌗ Overview
> 수학(0x0C)을 학습하고 문제를 풀이합니다. (@dadahae)

바킹독 수학 강의를 바탕으로 수학 이론과 문제를 풀이합니다.

## ⚒︎ Task
* [ ] 바킹독 알고리즘 강의 수학 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] Python, Swift에 관련하여 배열 정리
* [ ] 문제집 풀이
