### ISSUE TITLE
[Study] 투포인터(0x14)을 학습하고 문제를 풀이합니다 (@dadahae)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#14]
## ⌗ Overview
> 투포인터(0x14)을 학습하고 문제를 풀이합니다 (@dadahae)

바킹독 강의를 바탕으로 이론과 문제를 풀이합니다.

## ⚒︎ Task
> 바킹독의 강의 카운트와 알고킹 레포의 알고리즘 카운트는 같지 않습니다. 

* [ ] 바킹독 알고리즘 강의 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] 공부 내용 정리
* [ ] 문제집 풀이
