### ISSUE TITLE
[Study] 그래프(0x18)을 학습하고 문제를 풀이합니다.

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#18]
## ⌗ Overview
> 그래프(0x18)을 학습하고 문제를 풀이합니다.

바킹독 강의를 바탕으로 이론과 문제를 풀이합니다.

## ⚒︎ Task
* [ ] 바킹독 알고리즘 강의 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] 공부 내용 정리
* [ ] 문제집 풀이
