### ISSUE TITLE
[Study] 배열(0x01)을 학습하고 문제를 풀이합니다. (@dadahae)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#2]
## ⌗ Overview
> 배열(0x01)을 학습하고 문제를 풀이합니다. (@dadahae)

바킹독 0x03 배열 강의를 바탕으로 배열 이론과 문제를 풀이합니다.
시즌1에서 배열 강의는 스킵하고 넘어갔으므로 최초로 학습합니다.

## ⚒︎ Task
> 바킹독의 강의 카운트와 알고킹 레포의 알고리즘 카운트는 같지 않습니다. 

* [x] 바킹독 알고리즘 강의의 0x03 챕터 '배열' 학습
* [x] 강의에서 소개한 문제 풀이
* [x] Python, Swift에 관련하여 배열 정리
* [x] 문제집 풀이
