### ISSUE TITLE
[Study] 연결리스트(0x02)을 학습하고 문제를 풀이합니다. (@dadahae)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#3]
## ⌗ Overview
> 연결리스트(0x02)을 학습하고 문제를 풀이합니다. (@dadahae)

바킹독 '0x04 연결리스트' 강의를 바탕으로 연결리스트 이론과 문제를 풀이합니다.
시즌1에서 연결리스트 강의는 스킵하고 넘어갔으므로 최초로 학습합니다.

## ⚒︎ Task
> 바킹독의 강의 카운트와 알고킹 레포의 알고리즘 카운트는 같지 않습니다. 

* [ ] 바킹독 알고리즘 강의의 0x04 챕터 '연결리스트' 학습
* [ ] 강의 문제 풀이
* [ ] Python, Swift를 사용하여 연결리스트 내용 정리
* [ ] 문제집 풀이
