### ISSUE TITLE
[Study] 스택, 큐, 덱(0x03)을 학습하고 문제를 풀이합니다. (@dadahae)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#4]
## ⌗ Overview
> 스택, 큐, 덱(0x03)을 학습하고 문제를 풀이합니다. (@dadahae)

바킹독 0x04 스택, 0x05 큐, 0x06 덱 강의를 바탕으로 스택 이론과 문제를 풀이합니다.

## ⚒︎ Task
> 스택, 큐, 덱
* [ ] 바킹독 알고리즘 강의의 0x03 챕터 '스택' 학습
* [ ] 바킹독 알고리즘 강의의 0x03 챕터 '큐' 학습
* [ ] 바킹독 알고리즘 강의의 0x03 챕터 '덱' 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] Python, Swift에 관련하여 스택, 큐, 덱 정리
* [ ] 문제집 풀이
