### ISSUE TITLE
[Study] 재귀(0x0B)를 학습하고 문제를 풀이합니다. (@dahae0320)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#7]
## ⌗ Overview
>  재귀(0x0B)을 학습하고 문제를 풀이합니다. (@dahae0320)

바킹독 재귀 강의를 바탕으로 이론과 문제를 풀이합니다.

## ⚒︎ Task
* [ ] 바킹독 알고리즘 강의의 0x0B 챕터 '재귀' 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] Python, Swift에 관련하여 배열 정리
* [ ] 문제집 풀이
