### ISSUE TITLE
[Study] 백트래킹(0x07)을 학습하고 문제를 풀이합니다. (@dahae0320)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#8]
## ⌗ Overview
> 백트래킹(0x07)을 학습하고 문제를 풀이합니다. (@dahae0320)

바킹독 백트래킹 강의를 바탕으로 이론과 문제를 풀이합니다.

## ⚒︎ Task
* [ ] 바킹독 알고리즘 강의의 0x0C 챕터 '백트래킹' 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] Python, Swift에 관련하여 배열 정리
* [ ] 문제집 풀이
