### ISSUE TITLE
[Study] 정렬(0x09)을 학습하고 문제를 풀이합니다. (@dahae0320)

### ISSUE THREAD

**Issue by dahae0320** [BigkingStone/ArrrrrrrrrrrrrrrgoKing#9]
## ⌗ Overview
> 정렬(0x09)을 학습하고 문제를 풀이합니다. (@dahae0320)

정렬 배열 강의를 바탕으로 배열 이론과 문제를 풀이합니다.

## ⚒︎ Task
* [ ] 바킹독 알고리즘 강의의 0x0E 챕터 '정렬 Ⅰ' 학습
* [ ] 강의에서 소개한 문제 풀이
* [ ] Python, Swift에 관련하여 배열 정리
* [ ] 문제집 풀이
